name: Flutter CI

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "frontend/**" ]

defaults:
  run:
    working-directory: frontend

jobs:
  build_flutter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
